name: Change Tracking Markers File
  
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [published]
    inputs:
      Revisionversion:
        description: 'CURL Revision version'
        required: true
        default: '1'   

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      # This step builds a var with the release tag value to use later    
      - name: run curl
        id: testcases
        run: |
        
            version=$((${{github.event.inputs.Revisionversion}}+1))
            echo "newversion=$((version))"
            echo "CURLVERSION=$((version))" >> $GITHUB_OUTPUT                     
            curl -X 'POST' \
              'https://api.newrelic.com/graphql' \
              -H 'Content-Type: application/json' \
              -H 'API-Key: NRAK-IXMD84CHERKDM7LHK64S7M7D2FE' \
              --data-binary '{"query":"mutation {changeTrackingCreateDeployment(deployment: {version: \'"$version"'\", entityGuid: \"MzY1NTM3MnxBUE18QVBQTElDQVRJT058MTA2NzUyNzk1Nw\"}) {\n    deploymentId\n    entityGuid\n  }\n}\n", "variables":""}'
